$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: llama-3-2-1b-deployment
endpoint_name: llama-endpoint-v1
model: azureml:llama-3-2-1b@latest
code_configuration:
  code: .
  scoring_script: score.py
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest
instance_type: Standard_E4s_v3
instance_count: 1
app_insights_enabled: false
scale_settings:
  type: default 
