$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: llama-3-2-1b-deployment
endpoint_name: $(ENDPOINT_NAME)
model:
  path: $(MODEL_PATH)
code_configuration:
  code: .
  scoring_script: score.py
environment: 
  conda_file: environment/conda.yaml
  image: mcr.microsoft.com/azureml/cuda-11.8-cudnn8-ubuntu22.04:latest
instance_type: Standard_NC6s_v3
instance_count: 1 